import { Article, Feed, Group } from "./types";

export const mockGroups: Group[] = [
  { id: "g1", name: "今日摘要", iconName: "Sun", unreadCount: 12 },
  { id: "g2", name: "技术前沿", iconName: "Cpu", unreadCount: 84 },
  { id: "g3", name: "深度长文", iconName: "BookOpen", unreadCount: 37 },
  { id: "g4", name: "轻快简讯", iconName: "Zap", unreadCount: 56 },
  { id: "g5", name: "产品与设计", iconName: "PenTool", unreadCount: 28 },
  { id: "g6", name: "播客与视频", iconName: "PlayCircle", unreadCount: 19 },
];

export const mockFeeds: Feed[] = [
  { id: "f1", name: "Medium", unreadCount: 18, iconLetter: "M", iconColor: "#fff" },
  { id: "f2", name: "The Verge", unreadCount: 14, hasError: true, iconLetter: "V", iconColor: "#e53e3e" },
  { id: "f3", name: "少数派", unreadCount: 9, iconLetter: "π", iconColor: "#e53e3e" },
  { id: "f4", name: "阮一峰的网络日志", unreadCount: 6, isStale: true, iconLetter: "R", iconColor: "#a0aec0" },
  { id: "f5", name: "InfoQ 中文", unreadCount: 21, iconLetter: "iQ", iconColor: "#319795" },
  { id: "f6", name: "Wired", unreadCount: 10, iconLetter: "W", iconColor: "#3182ce" },
  { id: "f7", name: "Ars Technica", unreadCount: 7, hasError: true, iconLetter: "Ars", iconColor: "#dd6b20" },
];

export const mockArticles: Article[] = [
  {
    id: "a1",
    title: "Gemini 1.5: 更长上下文，更强推理能力",
    source: "The Verge",
    summary: "Google DeepMind 发布了 Gemini 1.5，支持高达 100 万 token 的上下文...",
    content: "Google DeepMind 今天发布了 Gemini 1.5，这是一款在多个维度上取得重大进步的多模态模型。最引人注目的是其上下文窗口扩展到了 100 万 token，相比上一代提升了 10 倍，这让处理超长文档、复杂代码库甚至长时视频成为可能。\n\n在推理能力方面，Gemini 1.5 在多个基准测试中超越了 GPT-4o 和 Claude 3 Opus，尤其在长程依赖和多步推理任务上表现突出。\n\n## 更长的上下文带来什么改变？\n\n过去，模型在处理长文本时往往需要截断或分块，这不可避免地导致信息丢失。Gemini 1.5 的超长上下文能力，使得一次性输入整本书、几十页的研究报告，甚至一小时的视频成为现实。\n\n除此之外，DeepMind 还在安全性、幻觉抑制和工具调用方面进行了多项优化，使得模型在真实应用场景中更加可靠。",
    url: "https://example.com/gemini-1-5",
    publishedAt: "28 分钟前",
    isRead: false,
    isStarred: false,
    tags: ["AI", "Google", "大模型"],
  },
  {
    id: "a2",
    title: "字节跳动开源 VEDB：面向大规模向量检索的数据库",
    source: "InfoQ 中文",
    summary: "VEDB 在检索性能和内存占用方面相比开源方案有显著提升，适用于...",
    content: "字节跳动开源 VEDB...",
    url: "https://example.com/vedb",
    publishedAt: "1 小时前",
    isRead: false,
    isStarred: false,
    tags: ["数据库", "开源"],
  },
  {
    id: "a3",
    title: "iOS 18 亮点：隐私沙盒与设备端 AI",
    source: "少数派",
    summary: "苹果在 WWDC24 上展示了多项隐私相关的新功能，并将部分 AI 能力...",
    content: "iOS 18 亮点介绍...",
    url: "https://example.com/ios-18",
    publishedAt: "2 小时前",
    isRead: false,
    isStarred: false,
    tags: ["Apple", "iOS"],
  },
  {
    id: "a4",
    title: "我在 10 年架构演进中学到的 7 件事",
    source: "Medium",
    summary: "系统设计没有银弹，但有可复用的原则。本文回顾了从单体到云原生...",
    content: "我在 10 年架构演进中学到的 7 件事...",
    url: "https://example.com/architecture",
    publishedAt: "3 小时前",
    isRead: true,
    isStarred: false,
    tags: ["架构设计"],
  },
  {
    id: "a5",
    title: "理解 RAG 的幻觉：原因与缓解策略",
    source: "阮一峰的网络日志",
    summary: "当大模型“一本正经地胡说八道”时，问题出在哪里？如何让 RAG 更可...",
    content: "理解 RAG 的幻觉...",
    url: "https://example.com/rag",
    publishedAt: "5 小时前",
    isRead: false,
    isStarred: false,
    tags: ["AI"],
  },
  {
    id: "a6",
    title: "浏览器渲染性能优化：2024 实战指南",
    source: "Wired",
    summary: "深入渲染流水线，了解如何识别并消除性能瓶颈。",
    content: "浏览器渲染性能优化...",
    url: "https://example.com/performance",
    publishedAt: "昨天 21:43",
    isRead: true,
    isStarred: false,
    tags: ["Web前端"],
  },
  {
    id: "a7",
    title: "macOS Sequoia 带来的开发者体验提升",
    source: "Ars Technica",
    summary: "Xcode、终端与系统工具的一些实用改进。",
    content: "macOS Sequoia...",
    url: "https://example.com/macos",
    publishedAt: "昨天 19:02",
    isRead: true,
    isStarred: false,
    tags: ["Apple", "开发"],
  }
];

export const mockTags = ["系统设计", "AI", "开源", "隐私", "产品", "Web3", "程序员", "工具", "阅读", "科学", "效率", "设计", "管理", "经济", "未来", "浏览器", "Rust", "安全", "数据", "哲学", "移动开发", "机器学习", "量化投资", "等等"];
